"""The contract graph: input → transformation → output, derived from code.

Nodes are artifact kinds (with their contracts) and registered stations
(the transformations). Because this renders the LIVE registries, the
generated document cannot drift from the implementation — regenerate with
``palimpsest factory graph --write-docs`` after any station or contract
change.
"""

from __future__ import annotations

import json
from pathlib import Path

from palimpsest.factory.config import PROJECT_ROOT
from palimpsest.factory.core import registry
from palimpsest.factory.core.contracts import CONTRACTS, SOURCE_KINDS
from palimpsest.factory.workspace.io import atomic_write_text

DEFAULT_DOC_PATH = PROJECT_ROOT / "docs" / "CONTRACTS.md"


def build() -> dict:
    return {
        "kinds": [
            {
                "kind": c.kind,
                "grain": c.grain,
                "format": c.format,
                "required": list(c.required),
                "store": c.store,
                "description": c.description,
            }
            for c in CONTRACTS.values()
        ],
        "stations": [
            {
                "station": s.name,
                "version": s.version,
                "grain": s.grain,
                "consumes": list(s.consumes),
                "produces": s.produces,
                "uses_model": s.uses_model,
            }
            for s in registry.all_stations()
        ],
    }


def to_json() -> str:
    return json.dumps(build(), indent=2)


def to_mermaid() -> str:
    lines = ["flowchart TB"]
    used_kinds = set()
    for station in registry.all_stations():
        used_kinds.update(station.consumes)
        used_kinds.add(station.produces)
        for kind in station.consumes:
            lines.append(f"  {kind} --> {station.name}")
        lines.append(f"  {station.name} --> {station.produces}")

    for station in registry.all_stations():
        model_mark = " ✱" if station.uses_model else ""
        lines.append(
            f'  {station.name}(["{station.name}{model_mark}<br/>'
            f'<i>{station.grain}</i>"])')
        lines.append(f"  style {station.name} fill:#eef2ec,stroke:#9ab08f")
    for kind in sorted(used_kinds):
        if kind in SOURCE_KINDS:
            lines.append(f'  {kind}[("{kind}")]')
            lines.append(f"  style {kind} fill:#fdf6e3,stroke:#c9b99a")
        else:
            lines.append(f'  {kind}["{kind}"]')
    return "\n".join(lines)


def write_docs(path: Path = DEFAULT_DOC_PATH) -> Path:
    data = build()
    parts = [
        "# The Contract Graph",
        "",
        "<!-- GENERATED by `palimpsest factory graph --write-docs` — do not edit. -->",
        "",
        "Everything in the factory is input → transformation → output. This is",
        "the live graph, rendered from the station and contract registries in",
        "code; if it disagrees with `docs/BLUEPRINT.html`, THIS file is right.",
        "",
        "```mermaid",
        to_mermaid(),
        "```",
        "",
        "✱ = makes model calls.",
        "",
        "## Artifact contracts",
        "",
        "| Kind | Grain | Format | Required fields | Stored at |",
        "|---|---|---|---|---|",
    ]
    for kind in data["kinds"]:
        store = kind["store"] or f"<kind>/<page_id>{_suffix(kind['format'])}"
        required = ", ".join(f"`{f}`" for f in kind["required"]) or "—"
        parts.append(
            f"| `{kind['kind']}` | {kind['grain']} | {kind['format']} "
            f"| {required} | `{store}` |")
        parts.append(f"| | | | *{kind['description']}* | |")
    parts += [
        "",
        "## Transformations",
        "",
        "| Station | Version | Grain | Consumes | Produces | Model |",
        "|---|---|---|---|---|---|",
    ]
    for station in data["stations"]:
        consumes = ", ".join(f"`{k}`" for k in station["consumes"])
        parts.append(
            f"| `{station['station']}` | {station['version']} | {station['grain']} "
            f"| {consumes} | `{station['produces']}` "
            f"| {'yes' if station['uses_model'] else 'no'} |")
    parts += [
        "",
        "Contracts are enforced twice at runtime: a station referencing an",
        "unknown kind fails at registration, and a JSON artifact missing its",
        "kind's required fields fails its cell before anything is written.",
        "",
    ]
    atomic_write_text(path, "\n".join(parts))
    return path


def _suffix(format_name: str) -> str:
    from palimpsest.factory.core.contracts import FORMAT_SUFFIX

    return FORMAT_SUFFIX[format_name]
