"""Built-in stations. Importing this package registers all of them."""

from palimpsest.factory.stations import (
    align,
    align_rfdetr,
    acquire,
    assemble_page,
    deframe,
    dewatermark,
    emend,
    flatten,
    finalize_edition,
    publish,
    read,
    read_omp,
    reconstruct,
    reference,
    render_epub,
    segment,
    survey,
    translate,
)

__all__ = [
    "acquire",
    "align",
    "align_rfdetr",
    "assemble_page",
    "deframe",
    "dewatermark",
    "emend",
    "flatten",
    "finalize_edition",
    "publish",
    "read",
    "read_omp",
    "reconstruct",
    "reference",
    "render_epub",
    "segment",
    "survey",
    "translate",
]
