from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

FOLIO_RE = re.compile(r"^f(\d+)([rv])$", re.IGNORECASE)
PAGE_RE = re.compile(r"^page_(\d+)$", re.IGNORECASE)


def _strip_final_suffix(path: Path) -> str:
    stem = path.stem
    if stem.endswith("_final"):
        return stem[:-6]
    return stem


def _page_sort_key(stem: str) -> tuple[int, int, int, str]:
    folio = FOLIO_RE.match(stem)
    if folio:
        side = 0 if folio.group(2).lower() == "r" else 1
        return (0, int(folio.group(1)), side, stem)
    page = PAGE_RE.match(stem)
    if page:
        return (1, int(page.group(1)), 0, stem)
    return (2, 0, 0, stem)


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _extract_lines(page: dict[str, Any], mode: str) -> list[tuple[int, str]]:
    lines: list[tuple[int, str]] = []
    columns = page.get("columns")
    if isinstance(columns, list):
        for col in columns:
            if not isinstance(col, dict):
                continue
            col_lines = col.get("lines", [])
            if not isinstance(col_lines, list):
                continue
            for line in col_lines:
                if not isinstance(line, dict):
                    continue
                text = line.get(mode)
                if text is None:
                    text = ""
                line_no = line.get("line")
                if not isinstance(line_no, int):
                    line_no = len(lines) + 1
                lines.append((line_no, str(text)))
        return lines

    zones = page.get("zones")
    if isinstance(zones, list):
        zones_sorted = sorted(
            (z for z in zones if isinstance(z, dict)),
            key=lambda z: z.get("order", 0),
        )
        for zone in zones_sorted:
            text_obj = zone.get("text", {})
            if not isinstance(text_obj, dict):
                continue
            text = text_obj.get(mode)
            if text is None:
                continue
            line_no = zone.get("order")
            if not isinstance(line_no, int):
                line_no = len(lines) + 1
            lines.append((line_no, str(text)))
    return lines


def _write_txt(out_path: Path, pages: list[dict[str, Any]], mode: str) -> None:
    with out_path.open("w", encoding="utf-8") as handle:
        for page in pages:
            handle.write(f"[{page['page_id']}]\n")
            for line_no, text in page[mode]:
                handle.write(f"{line_no}. {text}\n")
            notes = page.get("page_notes", [])
            if notes:
                for note in notes:
                    handle.write(f"[note] {note}\n")
            handle.write("\n")


def _tei_header(doc_id: str, generated_at: str) -> list[str]:
    return [
        "<teiHeader>",
        "  <fileDesc>",
        "    <titleStmt>",
        f"      <title>{escape(doc_id)} transcription</title>",
        "    </titleStmt>",
        "    <publicationStmt>",
        f"      <p>Generated by palimpsest on {escape(generated_at)}</p>",
        "    </publicationStmt>",
        "    <sourceDesc>",
        "      <p>Derived from manuscript page transcriptions.</p>",
        "    </sourceDesc>",
        "  </fileDesc>",
        "</teiHeader>",
    ]


def _write_tei(out_path: Path, pages: list[dict[str, Any]], mode: str, doc_id: str, generated_at: str) -> None:
    lines: list[str] = ["<?xml version=\"1.0\" encoding=\"UTF-8\"?>"]
    lines.append('<TEI xmlns="http://www.tei-c.org/ns/1.0">')
    lines.extend(_tei_header(doc_id, generated_at))
    lines.append("<text>")
    lines.append("  <body>")
    for page in pages:
        page_id = escape(page["page_id"])
        lines.append(f"    <div type=\"folio\" n=\"{page_id}\">")
        for line_no, text in page[mode]:
            safe_text = escape(text)
            lines.append(f"      <lb n=\"{line_no}\"/>{safe_text}")
        for note in page.get("page_notes", []):
            lines.append(f"      <note>{escape(str(note))}</note>")
        lines.append("    </div>")
    lines.append("  </body>")
    lines.append("</text>")
    lines.append("</TEI>")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _write_page_txt(out_path: Path, page: dict[str, Any], mode: str) -> None:
    with out_path.open("w", encoding="utf-8") as handle:
        handle.write(f"[{page['page_id']}]\n")
        for line_no, text in page[mode]:
            handle.write(f"{line_no}. {text}\n")
        for note in page.get("page_notes", []):
            handle.write(f"[note] {note}\n")


def _write_page_outputs(pages_dir: Path, pages: list[dict[str, Any]], doc_id: str, generated_at: str) -> list[dict[str, str]]:
    pages_dir.mkdir(parents=True, exist_ok=True)
    outputs = []
    for page in pages:
        page_id = page["page_id"]
        diplomatic_path = pages_dir / f"{page_id}_diplomatic.txt"
        normalized_path = pages_dir / f"{page_id}_normalized.txt"
        tei_path = pages_dir / f"{page_id}.xml"
        _write_page_txt(diplomatic_path, page, "diplomatic")
        _write_page_txt(normalized_path, page, "normalized")
        _write_tei(tei_path, [page], "normalized", doc_id, generated_at)
        outputs.append({
            "page_id": page_id,
            "diplomatic_txt": str(diplomatic_path),
            "normalized_txt": str(normalized_path),
            "tei_xml": str(tei_path),
        })
    return outputs


def assemble_book(transcriptions_dir: Path) -> dict[str, Any]:
    transcriptions_dir = transcriptions_dir.resolve()
    out_dir = transcriptions_dir.parent / "book"
    out_dir.mkdir(parents=True, exist_ok=True)

    final_files = sorted(
        transcriptions_dir.glob("*_final.json"),
        key=lambda p: _page_sort_key(_strip_final_suffix(p)),
    )

    pages: list[dict[str, Any]] = []
    for path in final_files:
        page_id = _strip_final_suffix(path)
        page = _read_json(path)
        pages.append({
            "page_id": page_id,
            "path": str(path),
            "diplomatic": _extract_lines(page, "diplomatic"),
            "normalized": _extract_lines(page, "normalized"),
            "page_notes": page.get("page_notes", []),
        })

    generated_at = datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
    doc_id = transcriptions_dir.parent.parent.name

    _write_txt(out_dir / "book_diplomatic.txt", pages, "diplomatic")
    _write_txt(out_dir / "book_normalized.txt", pages, "normalized")
    _write_tei(out_dir / "book.xml", pages, "normalized", doc_id, generated_at)
    page_outputs = _write_page_outputs(out_dir / "pages", pages, doc_id, generated_at)
    outputs_by_id = {item["page_id"]: item for item in page_outputs}

    pass1_stems = {
        _strip_final_suffix(p) for p in transcriptions_dir.glob("*_pass1.json")
    }
    final_stems = {_strip_final_suffix(p) for p in final_files}
    missing_final = sorted(pass1_stems - final_stems, key=_page_sort_key)

    index = {
        "doc_id": doc_id,
        "generated_at": generated_at,
        "total_pages": len(pages),
        "pages": [
            {
                "page_id": page["page_id"],
                "path": page["path"],
                "line_count": len(page["diplomatic"]),
                "outputs": outputs_by_id.get(page["page_id"]),
            }
            for page in pages
        ],
        "missing_final": missing_final,
    }
    (out_dir / "book_index.json").write_text(
        json.dumps(index, indent=2), encoding="utf-8"
    )

    return index
